name: Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly
      - name: Install Dependencies
        run: yarn
      - name: Update Modules
        run: yarn sync
      - name: Run Tests
        run: FOUNDRY_PROFILE=ci yarn test
      - name: Run Coverage
        run: forge coverage --report lcov
      - name: Install lcov
        run: sudo apt-get update && sudo apt-get install lcov
      - name: Remove unwanted files
        run: |
          lcov --remove lcov.info 'test/*' -o lcov.info
          lcov --remove lcov.info 'src/mocks/*' 'src/libraries/*' -o lcov.info
          lcov --remove lcov.info 'src/interfaces/*' 'src/upgradeability/*' -o lcov.info
          lcov --remove lcov.info 'script/*' -o lcov.info
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: .
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          files: ./lcov.info
          name: grappa-coverage
          verbose: true
